name: Create python Docker Image

on:
  workflow_dispatch:


jobs:
  checkenv:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "user name ${{github.actor}} token ${{secrets.GITHUB_TOKEN}}"

  create-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: '01 - checkout the code'
        uses: actions/checkout@main

      - name: '02 - setup python env'
        uses: actions/setup-python@v5
        with: 
          python-version: "3.10"

      - name: '03 - install dependencies'
        run: |
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt; fi

      - name: '04 - login to github registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{secrets.GITHUBUSERNAME}}
          password: ${{secrets.GITHUBTOKEN}}

      - name: Build and push
        run: |
          docker build . --tag ghcr.io/thatyolandawang/myspider:latest
          docker push ghcr.io/thatyolandawang/myspider:latest
