name: Create python Docker Image

on:
  workflow_dispatch


jobs:
  create-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: '01 - checkout the code'
        uses: actions/checkout@main

      - name: '02 - setup python env'
        uses: actions/setup-python@v5
        with: 
          python-version: "3.10"

      - name: '03 - install dependencies'
        run: |
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt; fi

      - name: '04 - login to github container registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: '05 Build and push the container'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: thatyolanda/myspider:latest